<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-11-24T10:59:08+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      settings.enable_for_registered_users
 * @group     minify_html
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'settings' => [
        'status' => false,
        'enable_for_registered_users' => false,
    ],
];
