<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-08-19T12:08:09+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      connections.concrete
 * @group     database
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'default-connection' => 'concrete',
    'connections' => [
        'concrete' => [
            'driver' => 'c5_pdo_mysql',
            'server' => 'localhost',
            'database' => 'medimagic',
            'username' => 'root',
            'password' => 'root',
            'character_set' => 'utf8',
            'collation' => 'utf8_unicode_ci',
        ],
    ],
];
